#%RAML 0.8
title: New API
version: v1
baseUri: http://192.168.56.1:8000/{version}
mediaType: application/json
documentation:
  - title: Introduction
    content: |
      API to manage the sales and replenishments of stock items and floats in our vending machines.
/sales:
  post:
    body:
      example: |
        {
          "machineId" : "ZX4102",
          "trayId" : "A1",
          "dateAndTime" : "2013-10-22 16:17:00",
          "exchange" : {
            "value" : 450,
            "in" : 500,
            "out" : 50
          } 
        }
  get:
    responses:
      200:
        body:
          example: |
            {
                "count" : 2,
                "sales" : [
                  {
                    "dateAndTime" : "2013-10-22 16:17:00",
                    "value" : 450,
                    "machineId" : "ZX4102",
                    "productId" : "Cad-CB1012"
                  },
                  {
                    "dateAndTime" : "2013-10-22 16:17:00",
                    "value" : 150,
                    "machineId" : "ZX5322",
                    "productId" : "CC-LB1"
                  }
                ],
                "totalValue" : 600
            }
/machines:
  get:
    responses:
      200:
        body:
          example: |
            {
              "count" : 3,
              "machines" : [
                {
                  "id" : "ZX4102",
                  "location" : "Starbuck's, 442 Geary Street, San Francisco, CA 94102"
                },
                {
                  "id" : "ZX5322",
                  "location" : "Starbuck's, 462 Powell Street, San Francisco, CA 94102"
                },
                {
                  "id" : "ZX6792",
                  "location" : "Cafe La Taza, 470 Post Street, San Francisco, CA 94102"
                }
              ]
            }
  /{machine}:
    get:
      responses:
        200:
          body:
            example: |
              {
                "id" : "ZX4102",
                "location" : "Starbuck's, 442 Geary Street, San Francisco, CA 94102",
                "sales" : [
                  {
                    "dateAndTime" : "2013-10-22 16:17:00",
                    "value" : 450,
                    "machineId" : "ZX4102",
                      "productId" : "Cad-CB1012"
                  },
                  {
                    "dateAndTime" : "2013-10-22 16:17:00",
                    "value" : 150,
                    "machineId" : "ZX5322",
                    "productId" : "CC-LB1"
                    }
                  ],
                "floatsToBeReplenished" : [20, 40, 20, 80, 20, 40, 40],
                "stockToBeReplenished" : 54
              }
/songs:
  description: Collection of available songs in Jukebox
  get:
    description: Get a list of songs based on the song title.
    queryParameters:
      songTitle:
        description: "The title of the song to search (it is case insensitive and doesn't need to match the whole title)"
        required: true
        minLength: 3
        type: string
        example: "Get L"
    responses:
      200:
        body:
          application/json:
            example: |
              "songs": [
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440000",
                    "songTitle": "Get Lucky"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440111",
                    "songTitle": "Loose yourself to dance"
                  },
                  {
                    "songId": "550e8400-e29b-41d4-a716-446655440222",
                    "songTitle": "Gio sorgio by Moroder"
                  }
                  ]
 
