#%RAML 0.8
title: My API
version: v1

baseUri: http://localhost:8000/{version}

schemas:
 - resou: |
    {
      "type": "object",
      "required": true,
      "properties": {
        "songTitle": {
          "type": "string",
          "required": true
        },
        "artistName": {
          "type": "string",
          "required": true,
          "minLength": 3,
          "maxLength": 36
        }
      }
    }
    
traits:
  - paged:
      queryParameters: 
        page: 
          description: page number
          type: number        
  - secured:
      queryParameters:

        access_token: 
          description: The token to get authorized
          type: string          

/song:
  description: A generic resource
  post:
    is: [ secured ] 
    responses:
      200:
        body:
          application/json:
            example: |
              { "status": "ok" }
  get:
    is: [secured, paged]
    responses:
      200:
        body:
          application/json:
            schema: resou
            example: |                            
             {
             "songTitle" : "La Neuvième Symphonie",
             "artistName" : "beethoven"          
             }
            
            # invalidate Schema example
            # [ {"id": 1, "description":"resource instance 1"}, 
            #  { "id": 2, "description":"resource instance 2"}]
            
