#%RAML 0.8
title: My API
version: v1

baseUri: http://localhost:8000/{version}

schemas:
 - resou: |
    {
      "type": "object",
      "required": true,
      "properties": {
        "songTitle": {
          "type": "string",
          "required": true
        },
        "machineId": {
          "type": "string",
          "required": true,
          "minLength": 36,
          "maxLength": 36
        }
      }
    }
    
traits:
  - paged:
      queryParameters: 
        page: 
          description: page number
          type: number        
  - secured:
      queryParameters:

        access_token: 
          description: The token to get authorized
          type: string          

/resource:
  description: A generic resource
  post:
    is: [ secured ] 
    responses:
      200:
        body:
          application/json:
            example: |
              { "status": "ok" }
  get:
    is: [secured, paged]
    responses:
      200:
        body:
          application/json:
            schema: resou
            example: | 
              [ {"id": 1, "description":"resource instance 1"}, 
              {"id": 1, "description":"resource instance 1"}]
