#%RAML 0.8
title: My API
version: v1

baseUri: http://localhost:8000/{version}

traits:
  - paged: !include includes/paged.raml     
  - secured: !include includes/secured.raml

/resource:
  description: A generic resource
  post:
    is: [ secured ] 
    responses:
      200:
        body:
          application/json:
            example: |
              { "status": "ok" }
  get:
    is: [secured, paged]
    responses:
      200:
        body:
          application/json:
            example: | 
              [ {"id": 1, "description":"resource instance 1"}, 
              {"id": 2, "description":"resource instance 2"}]
