#%RAML 0.8
title: My API
version: v1

baseUri: http://localhost:8000/{version}

traits:
  - paged: !include includes/paged.raml     
  - secured: !include includes/secured.raml

/resource:
  description: A generic resource
  post:
    is: [ secured ] 
    responses:
      200:
        body:
          application/json:
            example: |
              { "status": "ok" }
  get:
    is: [secured, paged]
    responses:
      200:
        body:
          application/json:
            example: | 
              [ {"id": 1, "description":"resource instance 1"}, 
              {"id": 2, "description":"resource instance 2"}]

/artists/{name}:
  get:
    is: [secured, paged]
    responses:
      200:
        body:
          schema: artist
          example: |
            {
              "firstName": "John Doe",
              "birthday": "2014-12-23T15:05:00.000Z",
              "aliasS": "jaydoe",
              "age": 5

            }
